# Generated by Django 5.1 on 2024-08-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='awards/')),
                ('icon', models.CharField(choices=[('flaticon-medal', 'Medal'), ('flaticon-trophy', 'Trophy')], max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=100)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('owned_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('credential_URL', models.URLField()),
            ],
            options={
                'ordering': ['-owned_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('descrip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='skills_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('flaticon-camp', 'Camp'), ('icon-book', 'Book'), ('icon-terminal', 'Terminal'), ('icon-whatsapp', 'Whatsapp'), ('flaticon-circuit-board', 'Circuit Board'), ('flaticon-bomberman', 'Bomberman')], max_length=200)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('discrip', models.TextField()),
                ('skills_used', models.ManyToManyField(to='myprofile.skills')),
            ],
        ),
    ]
